const ShopActionTypes = {
  FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
  FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
  FETCH_COLLECTIONS_ERROR: 'FETCH_COLLECTIONS_ERROR'
  // UPDATE_COLLECTIONS: "UPDATE_COLLECTIONS"
};

export default ShopActionTypes;
